# SPDX-FileCopyrightText: 2021-2024 Helmholtz-Zentrum hereon GmbH
#
# SPDX-License-Identifier: CC0-1.0

image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  # install boost from sourceforge as libboost-dev only provides 1.74 and
  # pyinterp requires at least 1.79
  - |
    wget -q https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source/boost_1_84_0.tar.bz2
    tar --bzip2 -xf boost_1_84_0.tar.bz2
    cd boost_1_84_0
    ./bootstrap.sh --prefix=/usr
    ./b2 install
    cd ..
    rm -r boost_1_84_0.tar.bz2 boost_1_84_0
  # install necessary libraries for pyinterp
  - apt-get update -y && apt-get install -y g++ cmake libeigen3-dev libgsl-dev python3-numpy
  - python -m pip install -U pip

test-package:
  stage: test
  script:
    - pip install build twine
    - make dist
    - twine check dist/*
  artifacts:
    name: python-artifacts
    paths:
      - "dist/*"
    expire_in: 7 days

test:
  stage: test
  variables:
    PIPENV_PIPFILE: "ci/matrix/${SCENARIO}/Pipfile"
    # disable sandboxing, otherwise chrome reports errors when the
    # container runs as root
    # https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#sandboxing-support
    QTWEBENGINE_DISABLE_SANDBOX: "true"
  script:
    # install necessary libraries for pyqt
    - apt-get install -y xvfb python3-pyqt5.qtwebengine
    - pip install pipenv
    - pipenv install
    - xvfb-run make pipenv-test
  parallel:
    matrix:
      - SCENARIO: default
  artifacts:
    name: pipfile
    paths:
      - "ci/matrix/${SCENARIO}/*"
    expire_in: 30 days
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

test-docs:
  stage: test
  script:
    # install necessary libraries for pyqt
    - apt-get install -y python3-pyqt5.qtwebengine
    - make dev-install
    # install PyQt5 (not part of requirements.txt because this is complicated
    # to install on different platforms)
    - pip install PyQt5 PyQtWebEngine
    - make -C docs html
    - make -C docs linkcheck
  artifacts:
    paths:
    - docs/_build


deploy-package:
  stage: deploy
  needs:
    - job: test-package
    - job: test-docs
    - job: test
  only:
    - master
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*



deploy-docs:
  stage: deploy
  only:
    - master
  needs:
    - test-docs
  image: node:21
  before_script:
    - npm install -g gh-pages@6.1.1
    - mkdir .gh-pages-cache
  script:
    # make sure, the DEPLOY_TOKEN is defined
    - >-
      [ ${CI_DEPLOY_TOKEN} ] ||
      echo "The CI_DEPLOY_TOKEN variable is not set. Please create an access
      token with scope 'read_repository' and 'write_repository'" &&
      [ ${CI_DEPLOY_TOKEN} ]
    - >-
      CACHE_DIR=$(realpath .gh-pages-cache)
      gh-pages
      --dotfiles
      --nojekyll
      --branch gh-pages
      --repo https://ci-user:${CI_DEPLOY_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
      --user "${CI_COMMIT_AUTHOR}"
      --message "CI Pipeline ${CI_PIPELINE_ID}, commit ${CI_COMMIT_SHORT_SHA}"
      --dist docs/_build/html
